# Generated by Django 3.2.3 on 2021-06-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_pagina_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='publicar',
            field=models.BooleanField(default=True),
        ),
    ]
