# Generated by Django 3.2.3 on 2021-05-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    fecha_ejemplo =(2021, 3, 14, 8, 28, 56, 265918)
    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=fecha_ejemplo, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
    ]
