# Generated by Django 3.2.3 on 2021-05-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_asesor_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesor',
            name='created',
        ),
    ]
