# Generated by Django 3.2.3 on 2021-05-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_remove_asesor_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
