# Generated by Django 3.2.3 on 2021-06-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_citas_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
