# Generated by Django 3.2.3 on 2021-06-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0008_auto_20210609_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='images/empresa', verbose_name='logo')),
            ],
        ),
    ]
