# Generated by Django 3.2.3 on 2021-05-23 22:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble', models.CharField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Terreno', 'Terreno'), ('Comercio', 'Comercio')], default='Casa', max_length=15)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('imagen', models.ImageField(blank=True, upload_to='images/landing', verbose_name='Imagen')),
                ('nivel', models.IntegerField(blank=True, verbose_name='Nivel')),
                ('m2_construccion', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('m2_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('num_habitaciones', models.IntegerField(blank=True, default=0, verbose_name='Numero de cuartos')),
                ('num_banos', models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2, verbose_name='Numero de baños')),
                ('estacionamiento', models.IntegerField(blank=True, default=0, verbose_name='Numero de estacionamientos')),
                ('amenidades', models.BooleanField(default=False)),
                ('notas', ckeditor.fields.RichTextField()),
                ('calle', models.CharField(blank=True, max_length=40)),
                ('numero_ext', models.CharField(blank=True, max_length=8)),
                ('numero_int', models.CharField(blank=True, max_length=4)),
                ('colonia', models.CharField(max_length=40)),
                ('ciudad', models.CharField(default='Tijuana', max_length=40)),
                ('estado', models.CharField(default='Baja California', max_length=40)),
                ('pais', models.CharField(default='Mexico', max_length=40)),
                ('codigo_postal', models.CharField(blank=True, max_length=6)),
                ('latitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True, verbose_name='longitud')),
                ('featured', models.BooleanField(default=True, verbose_name='Quieres que aparesca en la pagina principal?')),
                ('tipo_contrato', models.CharField(choices=[('Venta', 'Venta'), ('Renta', 'Renta')], default='Venta', max_length=15)),
                ('termino', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.asesor')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/inmuebles', verbose_name='Imagen')),
                ('alt', models.CharField(blank=True, max_length=40)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble')),
            ],
        ),
    ]
