# Generated by Django 3.2.3 on 2021-05-24 03:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='nivel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='notas',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=2500000, max_digits=12),
        ),
    ]
