# Generated by Django 3.2.3 on 2021-05-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_auto_20210523_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='m2_construccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m2_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='num_banos',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2, null=True, verbose_name='Numero de baños'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='num_habitaciones',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Numero de cuartos'),
        ),
    ]
