# Generated by Django 3.2.3 on 2021-05-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_auto_20210523_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebleimagen',
            old_name='casa',
            new_name='inmueble',
        ),
    ]
