# Generated by Django 3.2.3 on 2021-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_alter_inmuebleimagen_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
